#!/bin/sh
if mountpoint -q /target; then
	echo "Installing fstrim to /target"
	cp /fstrim /target
else
	echo "/target is not a mountpoint."
	echo "You can either:"
	echo "- re-run this container with -v /usr/local/bin:/target"
	echo "- extract the fstrim binary (located at /fstrim)"
fi
